sudo: required
services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d 
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-servcie-acount --key-file service-acount.json
  - gcloud config set project multe-k8s
  - gcloud config set computer/zone asia-southeast1-c
  - gcloud container cluster get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t baodi76/react-test -f ./client/Dockerfile.dev ./client

# for running scripts
script:
  - docker run -e CI=true baodi76/react-test npm test

#deploy from script --> deploy.sh
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master