apiVersion: skaffold/v2beta12
kind: Config
deploy:
  kubectl:
    manifests:
      # read all of yamal file
      - ./k8s/*
      #- ./k8s/client-deployment.yaml
      #- ./k8s/server-deployment.yaml
      #- ./k8s/worker-deployment.yaml

build:
  local:
    push: false
  artifacts:
    - image: baodi76/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
          - src: "src/**/*.css"
            dest: .
          - src: "src/**/*.html"
            dest: .
    - image: baodi76/multi-worker
      context: worker
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
    - image: baodi76/multi-server
      context: server
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "*.js"
            dest: .
